title: ElectroMaster
description: stay simple, stay naive
author: ElectroMaster
github: https://github.com/chenshipku
about:
#disqus_shortname: stackproblems
#google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-zhihu
      link: "https://www.zhihu.com/people/chenshiPKU/activities"
    - icon: fa-github
      link: "https://github.com/chenshipku"


urls:
    - text: About Me
      url: /about/


url: "https://chenshipku.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
